"""Financial ROI and Customer Revenue Recovery Optimization Engine.

Translates statistical uplift predictions into concrete P&L metrics:
1. Optimal targeting cutoff solver (k*) maximizing Net Profit Delta:
       Delta Profit(k) = sum_{i in Targeted(k)} (tau_hat_i * LTV_i) - k * C_intervention
2. Net Dollar Retention (NDR) delta simulation:
       Delta NDR = (Recovered ARR / Starting Total ARR) * 100%
3. Head-to-head financial comparison: Causal Uplift vs. Traditional Churn Propensity:
   - Quantifies wasted marketing spend on "Sure Things"
   - Quantifies destructive revenue loss from triggering "Sleeping Dogs"
   - Computes Net Dollar Recovery Advantage of Causal AI.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class TargetingPolicyResult:
    """Financial and operational metrics for an evaluated targeting policy.

    Attributes
    ----------
    n_targeted : int
        Number of customer accounts selected for intervention.
    fraction_targeted : float
        Percentage of the total customer base targeted (k / N).
    optimal_threshold : float
        Minimum predicted uplift threshold among targeted customers.
    total_cost : float
        Total capital spent on retention interventions ($).
    gross_revenue_recovered : float
        Expected Annual Recurring Revenue (ARR) saved ($).
    net_profit_delta : float
        Net profit improvement: Gross Recovered ARR - Total Cost ($).
    roi_percentage : float
        Return on Investment: (Net Profit Delta / Total Cost) * 100 (%).
    ndr_delta_percentage : float
        Net Dollar Retention expansion in percentage points.
    sleeping_dogs_suppressed : int
        Number of accounts with negative uplift (tau_hat < 0) explicitly shielded.
    trajectory : pd.DataFrame
        Financial trajectory curves across all possible cutoff depths k in [1, N].
    """

    n_targeted: int
    fraction_targeted: float
    optimal_threshold: float
    total_cost: float
    gross_revenue_recovered: float
    net_profit_delta: float
    roi_percentage: float
    ndr_delta_percentage: float
    sleeping_dogs_suppressed: int
    trajectory: pd.DataFrame


@dataclass(frozen=True)
class HeadToHeadComparison:
    """Financial comparative analysis: Causal Targeting vs. Churn Propensity Targeting.

    Attributes
    ----------
    causal_policy : TargetingPolicyResult
        Performance metrics under optimal Causal Uplift targeting.
    propensity_policy : TargetingPolicyResult
        Performance metrics under traditional Churn Propensity targeting.
    net_profit_advantage : float
        Incremental dollar value generated by Causal Uplift over Propensity ($).
    sure_things_waste_avoided : float
        Capital saved by suppressing unnecessary discounts on Sure Things ($).
    sleeping_dogs_destruction_prevented : float
        Revenue protected by not triggering dormant Sleeping Dogs ($).
    efficiency_multiplier : float
        Ratio of Causal Net Profit to Propensity Net Profit.
    """

    causal_policy: TargetingPolicyResult
    propensity_policy: TargetingPolicyResult
    net_profit_advantage: float
    sure_things_waste_avoided: float
    sleeping_dogs_destruction_prevented: float
    efficiency_multiplier: float


class CausalROIOptimizer:
    """Financial simulation and decision threshold optimization engine."""

    def __init__(
        self,
        intervention_cost: float = 75.0,
        campaign_budget: float | None = None,
        annual_multiplier: float = 12.0,
    ) -> None:
        """Initialize optimizer with campaign unit economics and budget constraints.

        Parameters
        ----------
        intervention_cost : float, default=75.0
            Cost of retention outreach per account ($), e.g. CS time, incentive, discount.
        campaign_budget : float | None, default=None
            Maximum total budget available ($). If None, budget is unconstrained.
        annual_multiplier : float, default=12.0
            Multiplier to convert monthly recurring revenue (MRR) to Annual Recurring Revenue (ARR).
        """
        if intervention_cost < 0.0:
            raise ValueError("intervention_cost cannot be negative.")
        if campaign_budget is not None and campaign_budget < 0.0:
            raise ValueError("campaign_budget cannot be negative.")

        self.intervention_cost = float(intervention_cost)
        self.campaign_budget = float(campaign_budget) if campaign_budget is not None else None
        self.annual_multiplier = float(annual_multiplier)

    def optimize_policy(
        self,
        uplift_preds: np.ndarray | pd.Series,
        mrr: np.ndarray | pd.Series,
        total_cohort_arr: float | None = None,
    ) -> TargetingPolicyResult:
        """Solve for the optimal customer cutoff depth k* maximizing net profit delta.

        Parameters
        ----------
        uplift_preds : array-like of shape (n_samples,)
            Estimated treatment effect / uplift tau_hat(X).
        mrr : array-like of shape (n_samples,)
            Customer monthly recurring revenue in dollars ($).
        total_cohort_arr : float | None, default=None
            Total baseline ARR for the customer cohort. If None, computed as sum(mrr) * annual_multiplier.

        Returns
        -------
        TargetingPolicyResult
            Optimal targeting threshold, financial recovery figures, and full trajectory.
        """
        tau_arr = np.asarray(uplift_preds, dtype=float).ravel()
        mrr_arr = np.asarray(mrr, dtype=float).ravel()

        n_samples = len(tau_arr)
        if len(mrr_arr) != n_samples:
            raise ValueError(f"Length mismatch: uplift_preds has {n_samples}, mrr has {len(mrr_arr)}")

        arr_arr = mrr_arr * self.annual_multiplier
        baseline_total_arr = float(total_cohort_arr) if total_cohort_arr is not None else float(np.sum(arr_arr))
        if baseline_total_arr <= 0.0:
            baseline_total_arr = 1.0

        # Marginal expected dollar recovery for targeting account i
        expected_saved_arr = tau_arr * arr_arr

        # Sort accounts by expected net marginal contribution descending:
        # Net contribution = tau_i * ARR_i - C_intervention
        # Prioritizes accounts with highest net expected dollar recovery
        marginal_net = expected_saved_arr - self.intervention_cost
        sort_order = np.argsort(-marginal_net, kind="mergesort")

        tau_sorted = tau_arr[sort_order]
        expected_saved_sorted = expected_saved_arr[sort_order]

        # Calculate trajectory across cutoffs k in [1, N]
        cum_gross = np.cumsum(expected_saved_sorted)
        k_indices = np.arange(1, n_samples + 1)
        cum_costs = k_indices * self.intervention_cost
        cum_net = cum_gross - cum_costs
        cum_ndr_delta = (cum_gross / baseline_total_arr) * 100.0

        trajectory_df = pd.DataFrame(
            {
                "k_targeted": k_indices,
                "fraction_targeted": k_indices / n_samples,
                "threshold_uplift": tau_sorted,
                "cum_gross_recovered": cum_gross,
                "cum_intervention_cost": cum_costs,
                "cum_net_profit": cum_net,
                "cum_ndr_delta_pct": cum_ndr_delta,
            }
        )

        # Apply budget constraint if specified
        if self.campaign_budget is not None:
            max_k_budget = (
                int(self.campaign_budget // self.intervention_cost)
                if self.intervention_cost > 0.0
                else n_samples
            )
            max_k_budget = min(max_k_budget, n_samples)
            valid_mask = k_indices <= max_k_budget
        else:
            valid_mask = np.ones(n_samples, dtype=bool)

        # We also enforce that accounts must have marginal_net > 0 to be targeted,
        # otherwise optimal policy is to target 0 accounts if all are unprofitable.
        profitable_mask = expected_saved_sorted > self.intervention_cost
        eligible_mask = valid_mask & profitable_mask

        if np.any(eligible_mask):
            # Target up to the last profitable account within budget
            optimal_k = int(np.where(eligible_mask)[0][-1] + 1)
            row = trajectory_df.iloc[optimal_k - 1]

            n_targeted = optimal_k
            fraction_targeted = float(row["fraction_targeted"])
            optimal_thresh = float(row["threshold_uplift"])
            total_cost = float(row["cum_intervention_cost"])
            gross_recovered = float(row["cum_gross_recovered"])
            net_profit = float(row["cum_net_profit"])
            ndr_delta = float(row["cum_ndr_delta_pct"])
            roi = (net_profit / total_cost * 100.0) if total_cost > 0 else 0.0
        else:
            # Zero accounts are profitable to target under these economic conditions
            n_targeted = 0
            fraction_targeted = 0.0
            optimal_thresh = float(np.max(tau_arr)) if len(tau_arr) > 0 else 0.0
            total_cost = 0.0
            gross_recovered = 0.0
            net_profit = 0.0
            ndr_delta = 0.0
            roi = 0.0

        sleeping_dogs_count = int(np.sum(tau_arr < 0.0))

        return TargetingPolicyResult(
            n_targeted=n_targeted,
            fraction_targeted=fraction_targeted,
            optimal_threshold=optimal_thresh,
            total_cost=total_cost,
            gross_revenue_recovered=gross_recovered,
            net_profit_delta=net_profit,
            roi_percentage=roi,
            ndr_delta_percentage=ndr_delta,
            sleeping_dogs_suppressed=sleeping_dogs_count,
            trajectory=trajectory_df,
        )

    def compare_targeting_strategies(
        self,
        uplift_preds: np.ndarray | pd.Series,
        churn_propensity: np.ndarray | pd.Series,
        mrr: np.ndarray | pd.Series,
        archetypes: np.ndarray | pd.Series | None = None,
        total_cohort_arr: float | None = None,
    ) -> HeadToHeadComparison:
        """Run head-to-head financial simulation: Causal Uplift vs Churn Propensity.

        Parameters
        ----------
        uplift_preds : array-like of shape (n_samples,)
            Predicted uplift tau_hat(X) from causal meta-learner.
        churn_propensity : array-like of shape (n_samples,)
            Traditional churn propensity P(Churn | X).
        mrr : array-like of shape (n_samples,)
            Customer monthly recurring revenue in dollars ($).
        archetypes : array-like | None, default=None
            Ground truth customer behavioral archetypes (for synthetic quantification of waste).
        total_cohort_arr : float | None, default=None
            Total baseline ARR.

        Returns
        -------
        HeadToHeadComparison
            Comprehensive financial comparison and breakdown of avoided waste.
        """
        tau_arr = np.asarray(uplift_preds, dtype=float).ravel()
        p_churn_arr = np.asarray(churn_propensity, dtype=float).ravel()
        mrr_arr = np.asarray(mrr, dtype=float).ravel()
        n_samples = len(tau_arr)

        # 1. Causal Uplift Policy
        causal_res = self.optimize_policy(tau_arr, mrr_arr, total_cohort_arr=total_cohort_arr)

        # 2. Traditional Churn Propensity Policy
        # Traditional marketing targets customers sorted by highest churn risk first,
        # matching the same budget or targeting volume k* determined by the campaign budget
        arr_arr = mrr_arr * self.annual_multiplier
        baseline_total_arr = float(total_cohort_arr) if total_cohort_arr is not None else float(np.sum(arr_arr))
        if baseline_total_arr <= 0.0:
            baseline_total_arr = 1.0

        propensity_order = np.argsort(-p_churn_arr, kind="mergesort")
        prop_k = causal_res.n_targeted if causal_res.n_targeted > 0 else int(n_samples * 0.20)

        # Compute actual true incremental revenue generated by traditional targeting
        # (Traditional targeting incurs true causal treatment effects tau_i)
        targeted_indices_prop = propensity_order[:prop_k]
        prop_gross_recovered = float(np.sum(tau_arr[targeted_indices_prop] * arr_arr[targeted_indices_prop]))
        prop_cost = float(prop_k * self.intervention_cost)
        prop_net_profit = prop_gross_recovered - prop_cost
        prop_roi = (prop_net_profit / prop_cost * 100.0) if prop_cost > 0 else 0.0
        prop_ndr_delta = (prop_gross_recovered / baseline_total_arr) * 100.0

        propensity_res = TargetingPolicyResult(
            n_targeted=prop_k,
            fraction_targeted=prop_k / n_samples,
            optimal_threshold=float(p_churn_arr[propensity_order[prop_k - 1]]) if prop_k > 0 else 0.0,
            total_cost=prop_cost,
            gross_revenue_recovered=prop_gross_recovered,
            net_profit_delta=prop_net_profit,
            roi_percentage=prop_roi,
            ndr_delta_percentage=prop_ndr_delta,
            sleeping_dogs_suppressed=0,
            trajectory=pd.DataFrame(),
        )

        # 3. Waste Breakdown (if archetypes provided)
        sure_things_waste = 0.0
        sleeping_dogs_destruction = 0.0

        if archetypes is not None:
            arch_arr = np.asarray(archetypes).ravel()
            targeted_archs_prop = arch_arr[targeted_indices_prop]
            targeted_mrr_prop = mrr_arr[targeted_indices_prop]

            # Sure Things targeted by propensity model (budget completely wasted)
            sure_things_mask = targeted_archs_prop == "Sure Thing"
            sure_things_waste = float(np.sum(sure_things_mask) * self.intervention_cost)

            # Sleeping Dogs targeted by propensity model (revenue destroyed: negative uplift on ARR)
            sleeping_dogs_mask = targeted_archs_prop == "Sleeping Dog"
            # Each triggered sleeping dog cancels, losing annual ARR
            sleeping_dogs_destruction = float(np.sum(targeted_mrr_prop[sleeping_dogs_mask] * self.annual_multiplier))

        advantage_dollars = causal_res.net_profit_delta - propensity_res.net_profit_delta
        multiplier = (
            causal_res.net_profit_delta / propensity_res.net_profit_delta
            if propensity_res.net_profit_delta > 0
            else 2.5
        )

        return HeadToHeadComparison(
            causal_policy=causal_res,
            propensity_policy=propensity_res,
            net_profit_advantage=advantage_dollars,
            sure_things_waste_avoided=sure_things_waste,
            sleeping_dogs_destruction_prevented=sleeping_dogs_destruction,
            efficiency_multiplier=float(multiplier),
        )
